services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./stock-prediction-be
    ports:
      - "8000:8000"
    volumes:
      - ./stock-prediction-be:/app
      - ./stock-prediction-ml:/stock-prediction-ml
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./stock-prediction-fe
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  redis_data:
